### PR TITLE
Added optional timeout parameter to call_taxii_service2 method

### PR DESCRIPTION
**Pull request by mbekavac**

### CODE REVIEW

**Comment by mbekavac** [comment]
Fix for https://github.com/TAXIIProject/libtaxii/issues/214

**Comment by gtback** [comment]
Thanks, @mbekavac !

I never knew about `socket._GLOBAL_DEFAULT_TIMEOUT`. Given that it's a "private" attribute of the `socket` module, would it make sense to just not include the `timeout` argument in the call to `urllib.request.urlopen()` if it's not provided as an argument to `call_taxii_service2`? This would let people use `socket.setdefaulttimeout()` during operation, and have that reflected in future requests without needing to pass it to `call_taxii_service2`.

Something like:

```python
def call_taxii_service2(..., timeout=None):
    ...
    if timeout:
        response = urllib.request.urlopen(req, timeout=timeout)
    else:  # Defaults to socket.getdefaulttimeout()
        response = urllib.request.urlopen(req)
```

I haven't done a lot with the `urllib` and `socket` modules, so if I'm misunderstanding, let me know :-)

**Comment by gtback** [comment]
I don't think the build failure is related to anything in this branch, but I'll look more closely at this.

**Comment by mbekavac** [comment]
The reason I wrote it that way is to reflect the similar usage in the same module (https://github.com/TAXIIProject/libtaxii/blob/master/libtaxii/clients.py#L410). However, I'd prefer to do it your way if there are no reasons against it.

**Comment by gtback** [comment]
Oh, well I guess I should change it there too :-). Thanks.

**Comment by mbekavac** [comment]
Code updated. On a side note, it seems that the build failure is related to interpreter issues (it can't find python2.6) rather than any errors in the source code.

**Comment by mbekavac** [comment]
Please note - I'll start using the changed code on Monday, so I'll let you know if these changes caused any problems after it's been running for a couple of days.

**Comment by gtback** [comment]
Looks good to me. Thanks! I want to get the build failures fixed in master before merging this in, but I think this is good to go. Thanks again, @mbekavac !

**Comment by mbekavac** [comment]
@gtback I'm not sure if you're aware of this, but the code is not compatible with Python2.6 since the https://github.com/TAXIIProject/libtaxii/commit/cb59ae873e267ed96c2a183ec16fa04c33244e76 commit. The sys.version_info is a tuple, not an object with .major and .minor attributes.

I believe there are two possible solutions: drop support for Python2.6 entirely (which will cause the build to complete in all cases) or fix both the codebase and the build scripts. The code at earlier versions works fine with Python2.6.

**Comment by gtback** [comment]
Thanks again, @mbekavac. I hadn't realized that. It would be fairly straightforward to fix, but we don't have any test coverage for that module, and since it's meant to interact with an actual server, it's not the easiest module to add tests for. 

None of that really impacts this PR, of course. I'll think about what the best approach is, while you're running this code locally to ensure there aren't any problems that result.

**Comment by mbekavac** [comment]
Yeah, sorry about hijacking the PR discussion.
The code has been live for quite some time now an there haven't been any problems with it.

**Pull request merged**
